### ISSUE TITLE
Positional arguments for log message not working

### ISSUE THREAD

**Issue by iterq1** [b2wdigital/aiologger#97]
Hi! I have a trouble with using positional message arguments with aiologger, e.g: `logger.info("Test %s", "message")`'.

I see following:
> Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiologger/logger.py", line 223, in _log
    extra=extra,
  File "/usr/local/lib/python3.7/site-packages/aiologger/records.py", line 72, in __init__
    f"Invalid LogRecord args type: {type(args[0])}. "
ValueError: Invalid LogRecord args type: <class 'int'>. Expected Mapping

However keyword arguments work fine: `logger.info("Test %(param)s", {"param": "message"})`.

I found type check on 70'th line of `records.py` which I think is the reason of exception:
`if len(args) != 1 or not isinstance(args[0], Mapping):`

So am I doing smth wrong or it's a bug?

**Comment by psdh** [comment]
I faced this same issue. Had to use keyword arguments to work around this.

From the code that you've mentioned, it seems to be specifically designed to work this way.

**Comment by iterq1** [comment]
Yep, kw args work fine.

> From the code that you've mentioned, it seems to be specifically designed to work this way.

Yep, but It seems strange for me, because now aiologger dosen't copy default logger interface, so using it on existing codebase causes really much changes.

So I want to understand why is this done as we see. And should it be fixed or not.

**Comment by daltonmatos** [comment]
Hello all,

In fact the code shows that it's written specifically not to support interpolation with extra args. And thinking about aiologger being a drop replacement for stdlib logging this should be fixed.

Does any of you would be willing to code this implementation? It could be in fact a copy paste from stdlib logging module, the only difference would be that unit test must be written in order to the PR to be approved by the CI pipeline.

For now the way to go is to use kwargs or to interpolate the final string before passing it to your logger.

**Comment by iterq1** [comment]
Hello, @daltonmatos
Thx for clarifying everything, I'll try to create PR for this issue in some days, if nobody do before.

**Comment by daltonmatos** [comment]
Thank you very much @iterq1! I will be happy to review your PR.

**Comment by daltonmatos** [comment]
Maybe a good start could be compare these two examples (log with extra args and with extra kwargs) and see how the stdlib logging module behaves in these situations.

This will be a good guide to this implementation.

**Comment by TensorTom** [comment]
I had to drop aiologger for now because of this issue.

**Comment by daltonmatos** [comment]
Hello all,

Anyone would like to submit a Pull Request to fix this?

Thanks,
