### ISSUE TITLE
Using aiologger.handlers.streams.AsyncStreamHandler in gunicorn logging

### ISSUE THREAD

**Issue by aeldaly-tc** [b2wdigital/aiologger#99]
I'm trying to configure to use the same logger we're using for the app. Here's what I have:

`gunicorn_conf.py`
```
import json
import multiprocessing
import os

workers_per_core_str = os.getenv("WORKERS_PER_CORE", "1")
web_concurrency_str = os.getenv("WEB_CONCURRENCY", None)
host = os.getenv("HOST", "0.0.0.0")
port = os.getenv("PORT", "80")
bind_env = os.getenv("BIND", None)
use_loglevel = os.getenv("APP_LOG_LEVEL", "info")
if bind_env:
    use_bind = bind_env
else:
    use_bind = f"{host}:{port}"

cores = multiprocessing.cpu_count()
workers_per_core = float(workers_per_core_str)
default_web_concurrency = workers_per_core * cores
if web_concurrency_str:
    web_concurrency = int(web_concurrency_str)
    assert web_concurrency > 0
else:
    web_concurrency = max(int(default_web_concurrency), 2)

# Gunicorn config variables
loglevel = use_loglevel
workers = web_concurrency
bind = use_bind
keepalive = 120
errorlog = "-"
logconfig = "/app/gunicorn_logging.conf"

# For debugging and testing
log_data = {
    "loglevel": loglevel,
    "workers": workers,
    "bind": bind,
    # Additional, non-gunicorn variables
    "workers_per_core": workers_per_core,
    "host": host,
    "port": port,
}
print(json.dumps(log_data))
```

`gunicorn_logging.conf`
```
[loggers]
keys=root, gunicorn.error, gunicorn.access

[handlers]
keys=console

[formatters]
keys=json

[logger_root]
level=INFO
handlers=console

[logger_gunicorn.error]
level=INFO
handlers=console
propagate=1
qualname=gunicorn.error

[logger_gunicorn.access]
level=INFO
handlers=console
propagate=0
qualname=gunicorn.access

[handler_console]
class=aiologger.handlers.streams.AsyncStreamHandler
formatter=json
args=(sys.stdout, )

[formatter_json]
class=json_log_formatter.JSONFormatter
```

`output`
```
dls_app_api_1  | Traceback (most recent call last):
dls_app_api_1  |   File "/usr/local/bin/gunicorn", line 10, in <module>
dls_app_api_1  |     sys.exit(run())
dls_app_api_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 61, in run
dls_app_api_1  |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
dls_app_api_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 223, in run
dls_app_api_1  |     super(Application, self).run()
dls_app_api_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
dls_app_api_1  |     Arbiter(self).run()
dls_app_api_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 60, in __init__
dls_app_api_1  |     self.setup(app)
dls_app_api_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 95, in setup
dls_app_api_1  |     self.log = self.cfg.logger_class(app.cfg)
dls_app_api_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/glogging.py", line 200, in __init__
dls_app_api_1  |     self.setup(cfg)
dls_app_api_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/glogging.py", line 256, in setup
dls_app_api_1  |     disable_existing_loggers=False)
dls_app_api_1  |   File "/usr/local/lib/python3.7/logging/config.py", line 79, in fileConfig
dls_app_api_1  |     handlers = _install_handlers(cp, formatters)
dls_app_api_1  |   File "/usr/local/lib/python3.7/logging/config.py", line 150, in _install_handlers
dls_app_api_1  |     h.setFormatter(formatters[fmt])
dls_app_api_1  | AttributeError: 'AsyncStreamHandler' object has no attribute 'setFormatter'
```

**Comment by daltonmatos** [comment]
Hello @aeldaly-tc,

in fact the base `Handler` class lacks the `setFormatter` method and the `logging.Handler` class has this method.

Would you be willing to write a Pull Request adding this method?

Thanks.

**Comment by daltonmatos** [comment]
The method should me added in the base class: `aiologger.handlers.base.Handler`

**Comment by aeldaly-tc** [comment]
Sure. I'd love to take a stab at it. Do you have any guidelines on testing, code formatting, etc.?

Also, how about this error:

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.7/site-packages/aiologger/formatters/json.py", line 141, in format
    if record.flatten and isinstance(record.msg, dict):
AttributeError: 'LogRecord' object has no attribute 'flatten'
```

Generated when using this logging config:
```
[loggers]
keys=root, gunicorn.error, gunicorn.access

[handlers]
keys=console

[formatters]
keys=json

[logger_root]
level=INFO
handlers=console

[logger_gunicorn.error]
level=INFO
handlers=console
propagate=1
qualname=gunicorn.error

[logger_gunicorn.access]
level=INFO
handlers=console
propagate=0
qualname=gunicorn.access

[handler_console]
class=logging.StreamHandler
formatter=json
args=(sys.stdout, )

[formatter_json]
class=aiologger.formatters.json.ExtendedJsonFormatter
```

**Comment by aeldaly-tc** [comment]
and here is the output if I use `JsonFormatter`

```
{"loglevel": "info", "workers": 4, "bind": "0.0.0.0:80", "workers_per_core": 1.0, "host": "0.0.0.0", "port": "80"}
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 61, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 223, in run
    super(Application, self).run()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 60, in __init__
    self.setup(app)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 95, in setup
    self.log = self.cfg.logger_class(app.cfg)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/glogging.py", line 200, in __init__
    self.setup(cfg)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/glogging.py", line 256, in setup
    disable_existing_loggers=False)
  File "/usr/local/lib/python3.7/logging/config.py", line 71, in fileConfig
    formatters = _create_formatters(cp)
  File "/usr/local/lib/python3.7/logging/config.py", line 119, in _create_formatters
    f = c(fs, dfs, stl)
TypeError: __init__() takes from 1 to 3 positional arguments but 4 were given
```

**Comment by aeldaly-tc** [comment]
I've taken a stab at this in an app I'm building. I'm seeing a few problems. Firstly, whenever there is a reference to a `record`, the documentation states that it is an `ExtendedLogRecord`, but in fact it's just a `LogRecord` causing the code to break, because `LogRecord` is missing `flatten`, `extra` and `serializer_kwargs` are missing from that object. Here's what I've attempted. It doesn't throw any errors any more, but it's also not logging. Any pointers would be helpful. Thanks.

`gunicorn_logging.conf`
```
[loggers]
keys=root, gunicorn.error, gunicorn.access

[handlers]
keys=console

[formatters]
keys=json

[logger_root]
level=INFO
handlers=console

[logger_gunicorn.error]
level=INFO
handlers=console
propagate=1
qualname=gunicorn.error

[logger_gunicorn.access]
level=INFO
handlers=console
propagate=0
qualname=gunicorn.access

[handler_console]
class=core.loggers.DLSAsyncStreamHandler
formatter=json
args=(sys.stdout, )

[formatter_json]
class=core.loggers.DLSFormatter
```

`core.loggers`
```
import logging
from logging import config as logging_config

from aiologger.formatters.json import ExtendedJsonFormatter
from aiologger.handlers.streams import AsyncStreamHandler
from aiologger.records import LogRecord


class DLSAsyncStreamHandler(AsyncStreamHandler):
    def setFormatter(self, fmt):
        """
        Set the formatter for this handler.
        """
        self.formatter = fmt


class ExtendedLogRecord(LogRecord):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.flatten = False
        self.extra = None
        self.serializer_kwargs = {"indent": 2, "sort_keys": True}


class DLSFormatter(ExtendedJsonFormatter):
    def format(self, record: LogRecord):
        extended_record = ExtendedLogRecord(
            name=record.name,
            level=record.levelno,
            pathname=record.pathname,
            lineno=record.lineno,
            msg=record.msg,
            # args=[record.args], # couldn't figure out how to properly set this attribute
            exc_info=record.exc_info,
            func=record.funcName,
            sinfo=record.stack_info,
        )
        return super().format(extended_record)


logging_config.fileConfig("/app/gunicorn_logging.conf")
logger = logging.getLogger()
logger.debug("often makes a very good meal of %s", "visiting tourists")
```

**Comment by daltonmatos** [comment]
> Sure. I'd love to take a stab at it. Do you have any guidelines on testing, code formatting, etc.?

Thanks for dedicating yout time to the project. About the guidelines: All is bundled into the CI pipeline. So there are basically 3 checks:

- Code formatting. You can format with `pipenv run fmt`
- Code linting with mypy: `pipenv run lint`
- And test coverage that is checked autmoatically.

All other details e can discuss during the review.

**Comment by daltonmatos** [comment]
About the `LogRecord`/`ExtendedLogRecord` problem I will have to take a closer look. Maybe we can have only one of these if we can make it backward compatible.

What do you think about splitting this issue? We have multiple problems here:

- Formatter without `setFormatter()` method
- The questionable usage of `LogRecord` and `ExtentedLogRecord`.

Maybe we could open two new issues and mentoin them here. This way we can discuss each problem separately.

What do you think?

**Comment by daltonmatos** [comment]
Now that I read better your example I'm now thinking if it's a good idea to use `logging.FileConfig` to configure a logger that is asynchronous.

What makes me think is that aiologger, although having a "sync interface" (def info(), def debug(), etc) it **requires** an I/O loop to be running. I don't know if mixing and async unaware configurer (logging.fileConfig) cloud bring new problems to whoever is using aiologger.

If we can guarantee that the "config phase" is always sync, that is, always calls sync methods (and that **do not** return any awaitables) then the usage of `logging.fileConfig` may bacame a reality and can be fully supported. And also maybe this could be a whole other discussion.
